[project]
name = "icland"
version = "0.1.0"
description = "Recreating Google DeepMind's XLand RL environment in JAX"
readme = "README.md"
authors = []
requires-python = ">=3.13"
dependencies = [
    "brax>=0.12.1",
    "mujoco>=3.2.6",
    "mujoco-mjx>=3.2.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.0.1",
    "ruff>=0.9.1",
]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
# Enable pydocstyle checks
# See: https://docs.astral.sh/ruff/rules/#pydocstyle-d
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"
